name: Rust Build Matrix
description: Generate a Rust Build Matrix.
author: reitermarkus
branding:
  icon: grid
  color: green

outputs:
  matrix:
    description: Build Matrix
    value: ${{ steps.generate-matrix.outputs.matrix }}

runs:
  using: composite
  steps:
    - name: Generate matrix
      id: generate-matrix
      run: |
        "${GITHUB_ACTION_PATH}/generate-matrix.sh"
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
