on: [pull_request, push]

name: CI

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: ./

      - run: cargo init --bin .

      - uses: ./
        env:
          CARGO_BUILD_TARGET: arm-unknown-linux-gnueabihf

      - run: |
          mkdir .cargo
          echo '[build]' >> .cargo/config.toml
          echo 'target = "arm-unknown-linux-gnueabihf"' >> .cargo/config.toml

      - uses: ./
