on: [pull_request, push]

name: CI

jobs:
  ci:
    name: ci (${{ matrix.name }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: default
            setup: ''
            expected-matrix: |
              [
                {
                  "os": "ubuntu-latest",
                  "toolchain": "stable",
                  "target": "x86_64-unknown-linux-gnu",
                  "use-cargo-feature-combinations": false,
                  "use-cross": false
                },
                {
                  "os": "macos-latest",
                  "toolchain": "stable",
                  "target": "x86_64-apple-darwin",
                  "use-cargo-feature-combinations": false,
                  "use-cross": false
                },
                {
                  "os": "macos-latest",
                  "toolchain": "stable",
                  "target": "aarch64-apple-darwin",
                  "use-cargo-feature-combinations": false,
                  "use-cross": false
                }
              ]
          - name: env
            setup: |
              echo 'CARGO_BUILD_TARGET=arm-unknown-linux-gnueabihf' >> "${GITHUB_ENV}"
            expected-matrix: |
              [
                {
                  "os": "ubuntu-latest",
                  "toolchain": "stable",
                  "target": "arm-unknown-linux-gnueabihf",
                  "use-cargo-feature-combinations": false,
                  "use-cross": true
                }
              ]
          - name: config
            setup: |
              mkdir .cargo
              echo '[build]' >> .cargo/config.toml
              echo 'target = "arm-unknown-linux-gnueabihf"' >> .cargo/config.toml
            expected-matrix: |
              [
                {
                  "os": "ubuntu-latest",
                  "toolchain": "stable",
                  "target": "arm-unknown-linux-gnueabihf",
                  "use-cargo-feature-combinations": false,
                  "use-cross": true
                }
              ]
          - name: windows
            setup: |
              mkdir .cargo
              echo '[build]' >> .cargo/config.toml
              echo 'target = "x86_64-pc-windows-msvc"' >> .cargo/config.toml
            expected-matrix: |
              [
                {
                  "os": "windows-latest",
                  "toolchain": "stable",
                  "target": "x86_64-pc-windows-msvc",
                  "use-cargo-feature-combinations": false,
                  "use-cross": false
                }
              ]

    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable

      - run: |
          set -euo pipefail

          cargo init --bin .

          ${{ matrix.setup }}

      - uses: ./
        id: generate-matrix

      - run: |
          set -euo pipefail

          jq <<< "${expected_matrix}" > expected.json
          jq <<< "${matrix}" > actual.json
          diff expected.json actual.json
        env:
          matrix: ${{ steps.generate-matrix.outputs.matrix }}
          expected_matrix: ${{ matrix.expected-matrix }}
