name: Update version tag

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: stairwaytowonderland/normalize-majorver@9714dd8f6590d38e8d9b9c9c6867581eabcb0be1 # v1
